-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.calendario_ctg_equipo
(
    id_calendario_ctg_equipo integer NOT NULL DEFAULT 'nextval('calendario_ctg_equipo_id_calendario_ctg_equipo_seq'::regclass)',
    num_reg_ctg_equipo numeric(20, 0) NOT NULL DEFAULT 'nextval('calendario_ctg_equipo_num_reg_ctg_equipo_seq'::regclass)',
    num_selec_calend_ctg numeric(20, 0) NOT NULL DEFAULT 'nextval('calendario_ctg_equipo_num_selec_calend_ctg_seq'::regclass)',
    id_exp_instructor integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.categ_inscripcion
(
    id_categ_inscripcion integer NOT NULL DEFAULT 'nextval('categ_inscripcion_id_categ_inscripcion_seq'::regclass)',
    id_historial_ingres integer NOT NULL,
    nueva_catg_infantil character(10) COLLATE pg_catalog."default" NOT NULL,
    nueva_catg_cadete character(10) COLLATE pg_catalog."default" NOT NULL,
    nueva_catg_juvenil character(10) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.categoria_equipo
(
    id_categoria_equipo integer NOT NULL,
    nombre_ctg_equipo character(10) COLLATE pg_catalog."default" NOT NULL,
    num_id_ctg_equipo numeric(10, 0) NOT NULL,
    "num_Ctg_equipo_cadete" numeric(10, 0) NOT NULL,
    "num_Ctg_equipo_juvenil" numeric(10, 0) NOT NULL,
    "num_Ctg_equipo_infantil" numeric(10, 0) NOT NULL,
    id_seleccion_equipos integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.crear_atleta
(
    id_crear_atleta integer NOT NULL DEFAULT 'nextval('crear_atleta_id_crear_atleta_seq'::regclass)',
    num_regis_atleta numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_atleta_num_regis_atleta_seq'::regclass)',
    nomb_apelld_atleta character(20) COLLATE pg_catalog."default" NOT NULL,
    telf_atleta numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_atleta_telf_atleta_seq'::regclass)',
    correo_atleta character(20) COLLATE pg_catalog."default" NOT NULL,
    edad_atleta numeric(3, 0) NOT NULL DEFAULT 'nextval('crear_atleta_edad_atleta_seq'::regclass)',
    fech_nacim_atleta numeric(10, 0) NOT NULL DEFAULT 'nextval('crear_atleta_fech_nacim_atleta_seq'::regclass)',
    sexo_atleta character(10) COLLATE pg_catalog."default" NOT NULL,
    direccion_atleta character(20) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.crear_instructor
(
    id_crear_instructor integer NOT NULL DEFAULT 'nextval('crear_instructor_id_crear_instructor_seq'::regclass)',
    num_regis_instructor numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_instructor_num_regis_instructor_seq'::regclass)',
    nomb_apelld_instructor character(20) COLLATE pg_catalog."default" NOT NULL,
    telf_instructor numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_instructor_telf_instructor_seq'::regclass)',
    correo_instructor character(20) COLLATE pg_catalog."default" NOT NULL,
    edad_instructor numeric(3, 0) NOT NULL DEFAULT 'nextval('crear_instructor_edad_instructor_seq'::regclass)',
    fech_nacim_instructor numeric(10, 0) NOT NULL DEFAULT 'nextval('crear_instructor_fech_nacim_instructor_seq'::regclass)',
    sexo_instructor character(10) COLLATE pg_catalog."default" NOT NULL,
    direccion_instructor character(20) COLLATE pg_catalog."default" NOT NULL,
    id_historial_de_ascenso integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.crear_regis_repre
(
    id_crear_regis_repre integer NOT NULL DEFAULT 'nextval('crear_regis_repre_id_crear_regis_repre_seq'::regclass)',
    num_regis_repre numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_regis_repre_num_regis_repre_seq'::regclass)',
    nomb_apelld_repre character(20) COLLATE pg_catalog."default" NOT NULL,
    telf_repre numeric(20, 0) NOT NULL DEFAULT 'nextval('crear_regis_repre_telf_repre_seq'::regclass)',
    correo_repre character(20) COLLATE pg_catalog."default" NOT NULL,
    edad_repre numeric(3, 0) NOT NULL DEFAULT 'nextval('crear_regis_repre_edad_repre_seq'::regclass)',
    fech_nacim_repre numeric(10, 0) NOT NULL DEFAULT 'nextval('crear_regis_repre_fech_nacim_repre_seq'::regclass)',
    sexo_repre character(10) COLLATE pg_catalog."default" NOT NULL,
    direccion_repre character(20) COLLATE pg_catalog."default" NOT NULL,
    id_num_puntaje_juegos integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.dias_jg_equipo
(
    id_dias_jg_equipo integer NOT NULL DEFAULT 'nextval('dias_jg_equipo_id_dias_jg_equipo_seq'::regclass)',
    dias_jg_cadete numeric(20, 0) NOT NULL DEFAULT 'nextval('dias_jg_equipo_dias_jg_cadete_seq'::regclass)',
    dias_jg_juvenil numeric(20, 0) NOT NULL DEFAULT 'nextval('dias_jg_equipo_dias_jg_juvenil_seq'::regclass)',
    dias_jg_infantil numeric(20, 0) NOT NULL DEFAULT 'nextval('dias_jg_equipo_dias_jg_infantil_seq'::regclass)',
    nombre_equipo_del_dia character(20) COLLATE pg_catalog."default" NOT NULL,
    id_seleccion_calend_ctg integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipo_asignado
(
    id_equipo_asignado integer NOT NULL DEFAULT 'nextval('equipo_asignado_id_equipo_asignado_seq'::regclass)',
    equipo_infantil character(20) COLLATE pg_catalog."default" NOT NULL,
    equipo_juvenil character(20) COLLATE pg_catalog."default" NOT NULL,
    equipo_cadete character(20) COLLATE pg_catalog."default" NOT NULL,
    num_tipos_entrenm numeric(20, 0) NOT NULL DEFAULT 'nextval('equipo_asignado_num_tipos_entrenm_seq'::regclass)',
    id_tipos_entrenm_clinicas integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipos_por_tipo_catg
(
    id_equipos_por_tipo_catg integer NOT NULL DEFAULT 'nextval('equipos_por_tipo_catg_id_equipos_por_tipo_catg_seq'::regclass)',
    nomb_equip_catg_cadete character(20) COLLATE pg_catalog."default" NOT NULL,
    nomb_equip_catg_juvenil character(20) COLLATE pg_catalog."default" NOT NULL,
    nomb_equip_catg_infantil character(20) COLLATE pg_catalog."default" NOT NULL,
    id_categoria_equipo integer NOT NULL,
    num_reg_equip_catg numeric(20, 0) NOT NULL DEFAULT 'nextval('equipos_por_tipo_catg_num_reg_equip_catg_seq'::regclass)'
);

CREATE TABLE IF NOT EXISTS public.exp_instructor
(
    id_exp_instructor integer NOT NULL DEFAULT 'nextval('exp_instructor_id_exp_instructor_seq'::regclass)',
    num_exp_trabj_anteriores numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_trabj_anteriores_seq'::regclass)',
    num_exp_curso_realizados numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_curso_realizados_seq'::regclass)',
    num_exp_curso_otros numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_curso_otros_seq'::regclass)',
    num_exp_curso_acondim numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_curso_acondim_seq'::regclass)',
    num_exp_curso_extratg numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_curso_extratg_seq'::regclass)',
    num_exp_curso_fisicos numeric(20, 0) NOT NULL DEFAULT 'nextval('exp_instructor_num_exp_curso_fisicos_seq'::regclass)',
    id_crear_regis_repre integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.historial_de_ascenso
(
    id_historial_de_ascenso integer NOT NULL DEFAULT 'nextval('historial_de_ascenso_id_historial_de_ascenso_seq'::regclass)',
    id_categoria_inscripcion integer NOT NULL,
    num_hist_ascenso_perdido numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_perdido_seq'::regclass)',
    num_hist_ascenso_ganados numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_ganados_seq'::regclass)',
    num_hist_ascenso_goles numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_goles_seq'::regclass)',
    num_hist_ascenso_empatados numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_empatados_seq'::regclass)',
    num_hist_ascenso_faltas numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_faltas_seq'::regclass)',
    num_hist_ascenso_penaltis numeric(2, 1) NOT NULL DEFAULT 'nextval('historial_de_ascenso_num_hist_ascenso_penaltis_seq'::regclass)'
);

CREATE TABLE IF NOT EXISTS public.historial_ingres
(
    id_historial_ingres integer NOT NULL DEFAULT 'nextval('historial_ingres_id_historial_ingres_seq'::regclass)',
    id_crear_atleta integer NOT NULL,
    num_hist_penaltis numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_hist_penaltis_seq'::regclass)',
    num_hist_faltas numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_hist_faltas_seq'::regclass)',
    num_hist_partd_ganados numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_hist_partd_ganados_seq'::regclass)',
    num_hist_partd_perdidos numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_hist_partd_perdidos_seq'::regclass)',
    num_hist_partd_empatados numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_hist_partd_empatados_seq'::regclass)',
    num_partd_goles numeric(20, 0) NOT NULL DEFAULT 'nextval('historial_ingres_num_partd_goles_seq'::regclass)'
);

CREATE TABLE IF NOT EXISTS public.num_juegos_jugados
(
    id_num_juegos_jugados integer NOT NULL DEFAULT 'nextval('num_juegos_jugados_id_num_juegos_jugados_seq'::regclass)',
    num_jg_jgados_emptads numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_num_jg_jgados_emptads_seq'::regclass)',
    num_jg_jgados_ganados numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_num_jg_jgados_ganados_seq'::regclass)',
    num_jg_jgados_perdidos numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_num_jg_jgados_perdidos_seq'::regclass)',
    num_jg_jugados_penaltis numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_num_jg_jugados_penaltis_seq'::regclass)',
    num_jg_jugados_faltas numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_num_jg_jugados_faltas_seq'::regclass)',
    nomb_equipo character(20) COLLATE pg_catalog."default" NOT NULL,
    selec_ctg_equipo numeric(20, 0) NOT NULL DEFAULT 'nextval('num_juegos_jugados_selec_ctg_equipo_seq'::regclass)',
    id_equipos_por_tipo_catg integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.num_puntaje_juegos
(
    id_num_puntaje_juegos integer NOT NULL DEFAULT 'nextval('num_puntaje_juegos_id_num_puntaje_juegos_seq'::regclass)',
    num_puntj_jgs_ganados numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_puntj_jgs_ganados_seq'::regclass)',
    num_puntj_jgs_perdidos numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_puntj_jgs_perdidos_seq'::regclass)',
    num_puntj_jgs_empatados numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_puntj_jgs_empatados_seq'::regclass)',
    num_puntj_jgs_goles numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_puntj_jgs_goles_seq'::regclass)',
    num_puntj_jgs_faltas numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_puntj_jgs_faltas_seq'::regclass)',
    num_registro_puntj_jgs numeric(20, 0) NOT NULL DEFAULT 'nextval('num_puntaje_juegos_num_registro_puntj_jgs_seq'::regclass)',
    id_num_juegos_jugados integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seleccion_calend_ctg
(
    id_seleccion_calend_ctg integer NOT NULL DEFAULT 'nextval('seleccion_calend_ctg_id_seleccion_calend_ctg_seq'::regclass)',
    num_id_ctg_cadete numeric(20, 0) NOT NULL DEFAULT 'nextval('seleccion_calend_ctg_num_id_ctg_cadete_seq'::regclass)',
    num_id_ctg_juvenil numeric(20, 0) NOT NULL DEFAULT 'nextval('seleccion_calend_ctg_num_id_ctg_juvenil_seq'::regclass)',
    num_id_ctg_infantil numeric(20, 0) NOT NULL DEFAULT 'nextval('seleccion_calend_ctg_num_id_ctg_infantil_seq'::regclass)',
    id_calendario_ctg_equipo integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.selecion_equipos
(
    id_selecion_equipos integer NOT NULL DEFAULT 'nextval('selecion_equipos_id_selecion_equipos_seq'::regclass)',
    num_equipos_cadetes numeric(20, 0) NOT NULL DEFAULT 'nextval('selecion_equipos_num_equipos_cadetes_seq'::regclass)',
    num_equipos_infantil numeric(20, 0) NOT NULL DEFAULT 'nextval('selecion_equipos_num_equipos_infantil_seq'::regclass)',
    num_equipos_juvenil numeric(20, 0) NOT NULL DEFAULT 'nextval('selecion_equipos_num_equipos_juvenil_seq'::regclass)',
    id_equipo_asignado integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tipos_entrenm_clinicas
(
    id_tipos_entrenm_clinicas integer NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_id_tipos_entrenm_clinicas_seq'::regclass)',
    id_crear_instructor integer NOT NULL,
    num_entrenm_clinicas_practica numeric(20, 0) NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_num_entrenm_clinicas_practica_seq'::regclass)',
    num_entrenm_clinicas_tacticas numeric(20, 0) NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_num_entrenm_clinicas_tacticas_seq'::regclass)',
    num_entrenm_clinicas_acond numeric(20, 0) NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_num_entrenm_clinicas_acond_seq'::regclass)',
    num_entrenm_clinicas_estratg numeric(20, 0) NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_num_entrenm_clinicas_estratg_seq'::regclass)',
    num_entrenm_clinicas_fisicas numeric(20, 0) NOT NULL DEFAULT 'nextval('tipos_entrenm_clinicas_num_entrenm_clinicas_fisicas_seq'::regclass)'
);

ALTER TABLE IF EXISTS public.calendario_ctg_equipo
    ADD FOREIGN KEY (id_exp_instructor)
    REFERENCES public.exp_instructor (id_exp_instructor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.categ_inscripcion
    ADD FOREIGN KEY (id_historial_ingres)
    REFERENCES public.historial_ingres (id_historial_ingres) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.categoria_equipo
    ADD FOREIGN KEY (id_seleccion_equipos)
    REFERENCES public.selecion_equipos (id_selecion_equipos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.crear_instructor
    ADD FOREIGN KEY (id_historial_de_ascenso)
    REFERENCES public.historial_de_ascenso (id_historial_de_ascenso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.crear_regis_repre
    ADD FOREIGN KEY (id_num_puntaje_juegos)
    REFERENCES public.num_puntaje_juegos (id_num_puntaje_juegos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dias_jg_equipo
    ADD FOREIGN KEY (id_seleccion_calend_ctg)
    REFERENCES public.seleccion_calend_ctg (id_seleccion_calend_ctg) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipo_asignado
    ADD FOREIGN KEY (id_tipos_entrenm_clinicas)
    REFERENCES public.tipos_entrenm_clinicas (id_tipos_entrenm_clinicas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipos_por_tipo_catg
    ADD FOREIGN KEY (id_categoria_equipo)
    REFERENCES public.categoria_equipo (id_categoria_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.exp_instructor
    ADD FOREIGN KEY (id_crear_regis_repre)
    REFERENCES public.crear_regis_repre (id_crear_regis_repre) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.historial_de_ascenso
    ADD FOREIGN KEY (id_categoria_inscripcion)
    REFERENCES public.categ_inscripcion (id_historial_ingres) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.historial_ingres
    ADD FOREIGN KEY (id_crear_atleta)
    REFERENCES public.crear_atleta (id_crear_atleta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.num_juegos_jugados
    ADD FOREIGN KEY (id_equipos_por_tipo_catg)
    REFERENCES public.equipos_por_tipo_catg (id_equipos_por_tipo_catg) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.num_puntaje_juegos
    ADD FOREIGN KEY (id_num_juegos_jugados)
    REFERENCES public.num_juegos_jugados (id_num_juegos_jugados) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.seleccion_calend_ctg
    ADD FOREIGN KEY (id_calendario_ctg_equipo)
    REFERENCES public.calendario_ctg_equipo (id_calendario_ctg_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.selecion_equipos
    ADD FOREIGN KEY (id_equipo_asignado)
    REFERENCES public.equipo_asignado (id_equipo_asignado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tipos_entrenm_clinicas
    ADD FOREIGN KEY (id_crear_instructor)
    REFERENCES public.crear_instructor (id_crear_instructor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;